"""change_decimal_places_on_density_and_moe

Revision ID: 072b2fae847d
Revises: efdf620228b8
Create Date: 2026-09-04 12:51:03.490396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072b2fae847d'
down_revision: Union[str, Sequence[str], None] = 'efdf620228b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_tests', 'calculated_density',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=6, scale=0),
               existing_nullable=False)
    op.alter_column('lab_tests', 'elastic_modulus',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=6, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_tests', 'elastic_modulus',
               existing_type=sa.Numeric(precision=6, scale=0),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('lab_tests', 'calculated_density',
               existing_type=sa.Numeric(precision=6, scale=0),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
