"""initial schema

Revision ID: c6afde0d5007
Revises: 
Create Date: 2026-07-18 14:12:45.776079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6afde0d5007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resin_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_letter', sa.String(length=1), nullable=False),
    sa.Column('press_operator', sa.String(length=50), nullable=False),
    sa.Column('line_operator', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_letter')
    )
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_ref', sa.Integer(), nullable=False),
    sa.Column('lab_test_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('panel_thickness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.Enum('MDF', 'PB', 'OSB', 'HDF', 'HID', 'IGN', name='paneltype'), nullable=False),
    sa.Column('actual_thickness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('calculated_density', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('moisture_content', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('internal_bond', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('bending_strength', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('elastic_modulus', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('thickness_swelling', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('water_absorption', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('formaldehyde_emission', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('formaldehyde_content', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_thickness > 0', name='ck_lab_tests_actual_thickness_positive'),
    sa.CheckConstraint('bending_strength >= 0', name='ck_lab_tests_bending_strength_nonnegative'),
    sa.CheckConstraint('calculated_density >= 0', name='ck_lab_tests_calculated_density_nonnegative'),
    sa.CheckConstraint('elastic_modulus >= 0', name='ck_lab_tests_elastic_modulus_nonnegative'),
    sa.CheckConstraint('formaldehyde_content >= 0', name='ck_lab_tests_formaldehyde_content_nonnegative'),
    sa.CheckConstraint('formaldehyde_emission >= 0', name='ck_lab_tests_formaldehyde_emission_nonnegative'),
    sa.CheckConstraint('internal_bond >= 0', name='ck_lab_tests_internal_bond_nonnegative'),
    sa.CheckConstraint('moisture_content >= 0', name='ck_lab_tests_moisture_content_nonnegative'),
    sa.CheckConstraint('panel_thickness > 0', name='ck_lab_tests_panel_thickness_positive'),
    sa.CheckConstraint('thickness_swelling >= 0', name='ck_lab_tests_thickness_swelling_nonnegative'),
    sa.CheckConstraint('water_absorption >= 0', name='ck_lab_tests_water_absorption_nonnegative'),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_ref')
    )
    op.create_table('production_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_ref', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.Enum('MDF', 'PB', 'OSB', 'HDF', 'HID', 'IGN', name='paneltype'), nullable=False),
    sa.Column('panel_length', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('panel_width', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('panel_thickness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('forming_line_speed', sa.Float(), nullable=False),
    sa.Column('press_temperature', sa.Float(), nullable=False),
    sa.Column('press_pressure', sa.Float(), nullable=False),
    sa.Column('press_factor', sa.Float(), nullable=False),
    sa.Column('resin_type_id', sa.Integer(), nullable=False),
    sa.Column('production_duration', sa.Float(), nullable=False),
    sa.Column('total_downtime', sa.Float(), nullable=False),
    sa.Column('resin_dosed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('paraffin_dosed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('urea_dosed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('percentage_recycled_material', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('panels_produced', sa.Integer(), nullable=False),
    sa.Column('panels_rejected', sa.Integer(), nullable=False),
    sa.CheckConstraint('forming_line_speed >= 0', name='ck_production_sheets_forming_line_speed_nonnegative'),
    sa.CheckConstraint('panel_length > 0', name='ck_production_sheets_panel_length_positive'),
    sa.CheckConstraint('panel_thickness > 0', name='ck_production_sheets_panel_thickness_positive'),
    sa.CheckConstraint('panel_width > 0', name='ck_production_sheets_panel_width_positive'),
    sa.CheckConstraint('panels_produced >= 0', name='ck_production_sheets_panels_produced_nonnegative'),
    sa.CheckConstraint('panels_rejected <= panels_produced', name='ck_production_sheets_panels_rejected_lte_produced'),
    sa.CheckConstraint('panels_rejected >= 0', name='ck_production_sheets_panels_rejected_nonnegative'),
    sa.CheckConstraint('paraffin_dosed >= 0', name='ck_production_sheets_paraffin_dosed_nonnegative'),
    sa.CheckConstraint('percentage_recycled_material >= 0 AND percentage_recycled_material <= 100', name='ck_production_sheets_percentage_recycled_material_range'),
    sa.CheckConstraint('press_factor >= 0', name='ck_production_sheets_press_factor_nonnegative'),
    sa.CheckConstraint('press_pressure >= 0', name='ck_production_sheets_press_pressure_nonnegative'),
    sa.CheckConstraint('press_temperature >= 0', name='ck_production_sheets_press_temperature_nonnegative'),
    sa.CheckConstraint('production_duration >= 0', name='ck_production_sheets_production_duration_nonnegative'),
    sa.CheckConstraint('resin_dosed >= 0', name='ck_production_sheets_resin_dosed_nonnegative'),
    sa.CheckConstraint('total_downtime >= 0', name='ck_production_sheets_total_downtime_nonnegative'),
    sa.CheckConstraint('urea_dosed >= 0', name='ck_production_sheets_urea_dosed_nonnegative'),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['resin_type_id'], ['resin_types.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_sheets_production_ref'), 'production_sheets', ['production_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_sheets_production_ref'), table_name='production_sheets')
    op.drop_table('production_sheets')
    op.drop_table('lab_tests')
    op.drop_table('shifts')
    op.drop_table('resin_types')
    op.drop_table('production_lines')
    # ### end Alembic commands ###
