"""add lab_tests production_sheet fk

Revision ID: efdf620228b8
Revises: c6afde0d5007
Create Date: 2026-08-28 00:01:57.638392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdf620228b8'
down_revision: Union[str, Sequence[str], None] = 'c6afde0d5007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_tests', sa.Column('production_sheet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lab_tests_production_sheet_id'), 'lab_tests', ['production_sheet_id'], unique=False)
    op.create_foreign_key(None, 'lab_tests', 'production_sheets', ['production_sheet_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_tests', type_='foreignkey')
    op.drop_index(op.f('ix_lab_tests_production_sheet_id'), table_name='lab_tests')
    op.drop_column('lab_tests', 'production_sheet_id')
    # ### end Alembic commands ###
